spring:
  application:
    name: customer-ui
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: actuator
      password: dev
      roles: ACTUATOR_ADMIN

server:
  port: 8081
#  servlet:
#    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11000/eureka/