spring:
  application:
    name: customer-ui
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: actuator
      password: dev
      roles: ACTUATOR_ADMIN

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/,http://localhost:11002/eureka/