spring:
  application:
    name: eureka-server
server:
  port: 11000
#  servlet:
#    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
