spring:
  application:
    name: eureka-server
server:
  port: 11001
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka_port}/eureka/
